### Numerical Python

http://www.numpy.org/  
Quickstart tutorial https://docs.scipy.org/doc/numpy/user/quickstart.html

In [2]:
# !pip install numpy
import numpy as np

1. Create numpy array

In [4]:
a = np.array([1, 2, 3])
# or
a = [1, 2, 3] # <-- type list
a = np.array(a)
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [10]:
a = np.array([[1, 2, 3], [15, 1, 3]])
a

array([[ 1,  2,  3],
       [15,  1,  3]])

In [89]:
# узнать размерность numpy array (строки, столбцы)
print(a.shape, '\n' , len(a))

(2,) 
 2


In [34]:
# numpy array comprehension 
a = np.arange(2, 10, 1) # с шагом 1
print(a, "\n\n" ,a.shape)

[2 3 4 5 6 7 8 9] 

 (8,)


In [35]:
# поменять размерность numpy массива
a = a.reshape(4, 2)
print(a)
a.shape

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


(4, 2)

In [37]:
a.resize(2, 4) # Return a new array with the specified shape.
a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [29]:
np.linspace(0, 2, 9) # 9 чисел от 0 до 2 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [41]:
b = np.zeros((2, 4)) # Return a new array of given shape and type, filled with zeros.
# np.ones() return filled with ones
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# np.vstack and np.hstack
np.vstack([a, b])

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.hstack([b, a])

array([[0., 0., 0., 0., 2., 3., 4., 5.],
       [0., 0., 0., 0., 6., 7., 8., 9.]])

#### Математические функции и операции с numpy arrays

In [46]:
a = np.array([-10, -1, 1, 5, 10])

In [51]:
f'sum: {a.sum()}, min: {a.min()}, max: {a.max()}, mean: {a.mean()}, std: {a.std()}'

'sum: 5, min: -10, max: 10, mean: 1.0, std: 6.663332499583072'

In [53]:
# return the index of the maximum and minimum values in the array.
a.argmin(), a.argmax()

(0, 4)

In [73]:
a = np.array([i*2 for i in range(1, 10)])
b = np.array([i for i in range(1, 10)])

In [74]:
b - a

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

In [75]:
a + b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [76]:
a / b

array([2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [77]:
a * b

array([  2,   8,  18,  32,  50,  72,  98, 128, 162])

In [79]:
a / 10

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [99]:
# numpy dot: Returns the dot product of a and b.
# Для двухмерных массивов это эквивалентно матричному умножению, 
# а для 1-D массивов - скалярному произведению векторов (без комплексного сопряжения).
# Для размерностей N это суммирующий продукт 
# по последней оси а и второй по последнему из b
a = np.array([1, 2])
b = np.array([10, 11])
print(np.dot(a, b)) # 1*10 + 2*11
print(a.dot(b))

32
32


##### Транспонирование

In [90]:
a = np.array([1, 2])

In [93]:
b = np.vstack([a, np.array([3, 4])])

In [98]:
print(b, end='\n\n')
print(b.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [100]:
b.dtype

dtype('int64')

In [104]:
b = b.astype('int8')

In [105]:
b.dtype

dtype('int8')

### Indexing

In [143]:
a = np.arange(10)**2

In [107]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [108]:
a[6]

36

In [109]:
# Получить интервал по индексу (прим. array[start:stop])
a[2:6]

array([ 4,  9, 16, 25])

In [110]:
a[-6]

16

In [144]:
a.resize(2, 5)

In [122]:
print(a[1][3])
print(a[1, 3])

64
64


In [135]:
a[:2, :-1]

array([[ 0,  1,  4,  9],
       [25, 36, 49, 64]])

In [139]:
# так же можно получить значения массива по булевой маске
mask = a > 4
print(mask, end='\n\n')
print(a[mask])

[[False False False  True  True]
 [ True  True  True  True  True]]

[ 9 16 25 36 49 64 81]


In [145]:
a[a <= 4] = 10
a

array([[10, 10, 10,  9, 16],
       [25, 36, 49, 64, 81]])

#### Pandas: series and dataframe 

In [146]:
# !pip install pandas
import pandas as pd

In [149]:
pd.Series(a[0])

0    10
1    10
2    10
3     9
4    16
dtype: int64

In [155]:
pd.Series(['1', 'x', 'z', 'd', None])

0       1
1       x
2       z
3       d
4    None
dtype: object

In [157]:
# Check is None
np.nan == None, np.nan == np.nan, np.isnan(np.nan)

(False, False, True)

##### Series

In [163]:
dct = {'name': 'Anna', 'height': 180, 'weight': np.nan, 'sports': 'Taekwondo'}

In [164]:
a = pd.Series(dct)

In [165]:
a

name           Anna
height          180
weight          NaN
sports    Taekwondo
dtype: object

In [166]:
a.index

Index(['name', 'height', 'weight', 'sports'], dtype='object')

In [168]:
a['name']

'Anna'

In [171]:
a[0]

'Anna'

##### Dataframe

In [206]:
dct = {'name': ['Anna', 'Boris', 'Jonh', 'Dmitry', 'Anna', 'Julia'], 
       'height': [np.random.randint(160, 189) for i in range(6)], 
       'weight': [np.nan, 65, 86, 77, 52, 46], 
       'sports': ['Taekwondo', 'Sumo', 'Basketball', 'Football', 'Golf', np.nan]}

In [245]:
df = pd.DataFrame(data=dct)
df

name  height  weight      sports
0    Anna     186     NaN   Taekwondo
1   Boris     166    65.0        Sumo
2    Jonh     173    86.0  Basketball
3  Dmitry     166    77.0    Football
4    Anna     176    52.0        Golf
5   Julia     176    46.0         NaN

In [246]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [249]:
df.index = [i*2 for i in a.index]

In [250]:
df

name  height  weight      sports
0     Anna     186     NaN   Taekwondo
2    Boris     166    65.0        Sumo
8     Jonh     173    86.0  Basketball
18  Dmitry     166    77.0    Football
32    Anna     176    52.0        Golf
50   Julia     176    46.0         NaN

In [251]:
df.loc[8]

name            Jonh
height           173
weight            86
sports    Basketball
Name: 8, dtype: object

In [252]:
df.iloc[2]

name            Jonh
height           173
weight            86
sports    Basketball
Name: 8, dtype: object

In [254]:
type(df.loc[8]), type(df.iloc[2])

(pandas.core.series.Series, pandas.core.series.Series)

In [256]:
df.loc[1:4]

name  height  weight sports
2  Boris     166    65.0   Sumo

In [257]:
df.iloc[1:4]

name  height  weight      sports
2    Boris     166    65.0        Sumo
8     Jonh     173    86.0  Basketball
18  Dmitry     166    77.0    Football

In [265]:
df.loc[2, 'sports'] # dont work with iloc

'Sumo'

In [263]:
df['sports'] # == df.sports

0      Taekwondo
2           Sumo
8     Basketball
18      Football
32          Golf
50           NaN
Name: sports, dtype: object

In [267]:
df[['sports', 'name']]

sports    name
0    Taekwondo    Anna
2         Sumo   Boris
8   Basketball    Jonh
18    Football  Dmitry
32        Golf    Anna
50         NaN   Julia

#### need more <s>minerals</s> rows

In [268]:
# Load Titanic dataframe
df = pd.read_csv('data/train.csv')

In [276]:
df.shape

(891, 12)